[package]
name = "wiivff"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
byteorder-pack = "0.1.0"
clap = { version = "4.0.26", features = ["derive"] }
thiserror = "1.0.37"

